version: '3.4'

# Must be run behind a Traefik v2 reverse proxy
services:
  attestation:
    # Uncomment below and comment image field if you want to build yourself
    # build:
    #   context: .
    image: quay.io/jfroment/attestation-deplacement:latest
    container_name: attestation
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.attestation.rule=Host(`attestation.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.attestation.entrypoints=secure"
      - "traefik.http.routers.attestation.tls.certresolver=le"
      - "traefik.docker.network=traefik-network"

networks:
  default:
    external:
      name: traefik-network